# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [1]:
import numpy as np

#### Set the seed to 0

In [2]:
np.random.seed(0)

#### Create an array of 10 zeros 

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [5]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [13]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50 (in order)

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [16]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

#### Create a 5x5 matrix with values ranging from 0 to 8

In [19]:
np.random.randint(low=0,high=8,size=(5,5))

array([[0, 1, 1, 1, 7],
       [0, 7, 2, 4, 7],
       [3, 6, 3, 2, 7],
       [4, 2, 0, 0, 4],
       [5, 5, 6, 0, 4]])

#### Create a 3x3 identity matrix

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [21]:
np.random.random()

0.38648898112586194

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [27]:
np.random.random_sample((5,5))

array([[0.28280696, 0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136],
       [0.58651293, 0.02010755, 0.82894003, 0.00469548, 0.67781654]])

#### Create the following matrix (hint: use `linspace` with `reshape`):

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

#### Create an array of 20 linearly spaced points between 0 and 1:

In [38]:
mat = np.linspace(0,1,100).reshape((10,10,-1))
mat
# np.reshape(np.linspace(0,1),(10,10))

array([[[0.        ],
        [0.01010101],
        [0.02020202],
        [0.03030303],
        [0.04040404],
        [0.05050505],
        [0.06060606],
        [0.07070707],
        [0.08080808],
        [0.09090909]],

       [[0.1010101 ],
        [0.11111111],
        [0.12121212],
        [0.13131313],
        [0.14141414],
        [0.15151515],
        [0.16161616],
        [0.17171717],
        [0.18181818],
        [0.19191919]],

       [[0.2020202 ],
        [0.21212121],
        [0.22222222],
        [0.23232323],
        [0.24242424],
        [0.25252525],
        [0.26262626],
        [0.27272727],
        [0.28282828],
        [0.29292929]],

       [[0.3030303 ],
        [0.31313131],
        [0.32323232],
        [0.33333333],
        [0.34343434],
        [0.35353535],
        [0.36363636],
        [0.37373737],
        [0.38383838],
        [0.39393939]],

       [[0.4040404 ],
        [0.41414141],
        [0.42424242],
        [0.43434343],
        [0.44444444],
  

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [39]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
np.setdiff1d(np.arange(12,26),np.array([16,21])).reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [51]:
np.arange(20,21)

array([20])

```python 
[Output]:
20
```

In [54]:
np.arange(2,13,5).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [55]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [56]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

### Conditional Indexing (AKA fancy indexing)

In [94]:
import numpy as np
np.random.seed(0)

In [95]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

#### Select all elements that are greater than 5.

In [59]:
 np.extract(mat > 5 , mat)

array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

#### Select all rows where the first element is less than or equal to 20.

In [71]:
mat[mat[:,0]<=20]

array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

ini_array1[ini_array1<0] = 0### Replace all negative elements with 0.

In [74]:
mat[mat<0] = 0
mat

array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Calculate the sum of all elements that are less than or equal to 5.

In [75]:
sum(mat[mat<=5])

5

Expected result: `5`

### Calculate the mean of all elements in the last column.

In [76]:
np.mean(mat[:-1])

20.2

Expected result: `20.2`

#### Count the number of elements that are not equal to 0.

In [77]:
np.count_nonzero(mat)

21

Expected result: `21`

#### Replace all elements equal to the maximum value of the matrix with 0.

In [79]:
mat[mat == np.max(mat)]=0
mat

array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Math on rows and columns

#### Add 5 to a all mat elements

In [84]:
mat = mat + 5
mat

array([[44, 47,  5,  5,  5],
       [ 5, 39,  9, 19, 21],
       [50, 36, 23,  6, 24],
       [24, 12,  5, 38, 39],
       [23, 46, 24, 17, 37]])

#### Get the sum of all the values in mat

In [86]:
np.sum(mat)

603

#### Get the standard deviation of the values in mat

In [87]:
np.std(mat)

15.007518115931095

#### Get the sum of all the columns in mat

In [96]:
mat.sum(0)

array([119, 155,  85,  55,  99])

#### Get the sum of all the rows in mat

In [97]:
mat.sum(1)

array([122,  66, 114,  89, 122])

# Great Job!